Repository ununu-p2p/ink-desktop, pull requests merged in 2020-01, with the labels that each got.

#17 update all outdated minor dependencies
  package-lock.json
  package.json
Labels: tooling

#24 fix some docs wordings
  .env.example
  README.md
  docs/setup.md
Labels: documentation

#29 Add Basic CI/CD Pipeline with a dummy Test
  .gitignore
  .travis.yml
  main/test/res/a/d/audio.aif
  main/test/res/a/d/audio.aif.asd
  main/test/res/project/a.als
  main/test/test-init.js
  package-lock.json
  package.json
Labels: backend, enhancement, tooling

#30 Add login page
  main/background.js
  renderer/components/Header.js
  renderer/pages/home.js
  renderer/pages/login.js
  renderer/pages/project/waveform.png
Labels: enhancement, frontend

#21 separate backend process
  backend/handlers.js
  lib/config.js
  lib/git-server.js
  lib/git/graph.js
  lib/git/utils.js
  lib/ink-file.js
  lib/parser.js
  lib/project.js
  lib/store/project-store.js
  lib/store/store.js
  lib/store/user-store.js
  lib/utils/array.js
  main/app.js
  main/backend.js
  main/background.js
  main/helpers/fork-backend.js
  main/lib/store/store.js
  main/lib/store/user-store.js
  package-lock.json
  package.json
  renderer/components/Spinner.js
  renderer/effects/useProjectState.js
  renderer/effects/useProjects.js
  renderer/effects/useUser.js
  renderer/layout/animations.js
  renderer/lib/mail.js
  renderer/lib/requestFromWorker.js
  renderer/pages/home.js
  renderer/pages/login.js
  renderer/pages/project/[id].js
Labels: backend

#33 fix changed import path for `ink-file`
  main/test/test-init.js
Labels: bug

#34 Add delete project endpoint
  backend/handlers.js
  lib/store/project-store.js
Labels: backend, enhancement

#36 Add parserManager and first version Resource Manger
  lib/parser.js
  lib/project.js
  lib/resource.js
  package-lock.json
  package.json
Labels: backend
