Repository ununu-p2p/ink-desktop, pull requests merged in 2020-04, with the labels that each got.

#90 mitigate next.js security vulnerability
  package-lock.json
  package.json
Labels: vulnerability

#87 project synchronization (push/pull) state
  backend/handlers.js
  backend/index.js
  lib/git/utils.js
  lib/project.js
  main/app.js
  main/background.js
  main/helpers/fork-backend.js
  nextron.config.js
  renderer/components/Dashboard.js
  renderer/components/Project/Invite.js
  renderer/components/Project/index.js
  renderer/components/SyncStatus.js
  renderer/effects/useBackendRequest.js
  renderer/effects/useBackendSubscription.js
  renderer/effects/useProjectState.js
  renderer/effects/useProjects.js
  renderer/lib/addBackendSubscription.js
  renderer/lib/backend.js
  renderer/lib/requestFromWorker.js
  renderer/pages/_app.js
  renderer/pages/login.js
Labels: backend, frontend

#100 hotfix: glob ignore
  lib/parser.js
  renderer/components/Project/Invite.js
Labels: bug

#101 Add travis encrypted release key, Modify the env variable names
  .travis.yml
Labels: bug

#103 Correct the CI/CD pipeline
  .travis.yml
Labels: bug
